services:
  - type: web
    name: realtime-editor
    env: node
    buildCommand: npm install && NODE_OPTIONS=--max_old_space_size=2048 npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true